### ISSUE TITLE
Create a SchemaOrg Example: Software Source Code

### ISSUE THREAD

**Issue by Castronova** [I-GUIDE/data-catalog#12]
Explore how SchemaOrg properties can be used to describe a software source code. The outcomes of this task will be:

A document containing:
  -  [ ] A JSON+LD example containing required metadata
  -  [ ] A JSON+LD example containing recommended metadata
  -  [ ] A JSON+LD example for a Jupyter notebook stored in HydroShare

**Comment by igarousi** [comment]
The example is created. Here is the link: https://github.com/I-GUIDE/data-catalog/blob/main/schema/sourcecode.md
