### ISSUE TITLE
Create Poster for the IGUIDE AHM

### ISSUE THREAD

**Issue by Castronova** [I-GUIDE/data-catalog#17]
Poster should highlight the various aspects of the Dataset Catalog prototype.

**Comment by Castronova** [comment]
@sblack-usu @aaraney @horsburgh Please review the poster linked below. This is still a work in progress but I would like feedback from all of you sooner rather than later. I plan to send this off for printing by Monday.

https://docs.google.com/presentation/d/1SCfvYd4T3JSb2YgIqA44FQeVwiTuySkn/edit?usp=sharing&ouid=112456855651091910995&rtpof=true&sd=true

**Comment by sblack-usu** [comment]
I don't have access to the document.  I'm not sure I have much else to add to it, I think you did a great job putting it together @Castronova.

**Comment by aaraney** [comment]
@sblack-usu, you should now.

**Comment by aaraney** [comment]
@Castronova, i've made some edits to the poster. I duplicated the slide and listed my changes in the duplicated slides notes section.
