### ISSUE TITLE
Encoding Format

### ISSUE THREAD

**Issue by Castronova** [I-GUIDE/data-catalog#22]
SchemaOrg encoding format should use MIME Types

https://www.baeldung.com/linux/file-mime-types#:~:text=A%20MIME%20type%20consists%20of,a%20type%20and%20a%20subtype.&text=Currently%2C%20there%20are%20ten%20registered,multipart%2C%20text%2C%20and%20video.

**Comment by igarousi** [comment]
Yes, we used encoding formats based on MIME types.
