### ISSUE TITLE
Core Metadata Definition

### ISSUE THREAD

**Issue by Castronova** [I-GUIDE/data-catalog#4]
## Assumptions

1. Everything is expressed as a SchemaOrg CreativeWork
2. A "Catalog DataSet" may consist of a single CreativeWork or have associative relationships (e.g. child, parent, sibling, etc.) with other CreativeWorks.
3. Any "valid" SchemaOrg representation is allowed
4. Datasets that contain multiple content items (e.g. HS resource) should consist of a higher-level dataset associated with content-level datasets.

### Required Metadata

**Thing**
- url: 1
- name: 1
- description: 1

**Creative Work**
- Associated Person: 1+ (creator | author | owner | maintainer | producer | editor )
- hasPart: 1+ 

### Recommended Metadata

[Creative Work Definition](https://schema.org/CreativeWork)

**Thing**
- url: 1
- name: 1
- description: 1

**Creative Work**
- Associated Person: 1+ (creator | author | owner | maintainer | producer | editor )
- hasPart: 1+ 
- isPartOf: 0+

**Comment by Castronova** [comment]
## "Scientific DataSet"

### Required Metadata

Example: a single file or HS Aggregation; shapefile, raster, netcdfs, geopackage, jupyter notebook etc. 

**Creative Work**
- Associated Person: 1+ (creator | author | owner | maintainer | producer | editor )
- isPartOf: 1+
- AssociatedMedia: 1+ (MediaObject)
  - contentSize: 1
  - contentUrl: 1
  - encodingFormat: 1


### Recommended Metadata

**Thing**
- url: 0, 1
- name: 0, 1
- description: 0, 1

**Creative Work**
- Associated Person: 1+ (creator | author | owner | maintainer | producer | editor )
- hasPart: 0+ 
- isPartOf: 1+
- AssociatedMedia: 1+ (MediaObject)
  - contentSize: 1
  - contentUrl: 1
  - encodingFormat: 1
  - sha256: 0, 1
- CreativeWork Subtype: 0, 1 (e.g. Dataset, SoftwareCode, SoftwareApplication->WebApplication)

**Comment by igarousi** [comment]
Core metadata is completed. Here is the link: https://github.com/I-GUIDE/data-catalog/blob/main/schema/core.md
