### ISSUE TITLE
Remove Date type from core schema

### ISSUE THREAD

**Issue by Castronova** [I-GUIDE/data-catalog#48]
Discussion from Slack:

**Pabitra**
>  It seems from our schema specification (https://github.com/I-GUIDE/data-catalog/blob/main/schema/core.md#dates), that we should be supporting both date and datetime for dateCreated, dateModified, and datePublished. However, the current implementation of pydantic model supports only datetime. I remember in the initial implementation we had both date and datetime. 
 may know why we removed the support for date. Should I add date back?

**Jeff**
> do we need both here? A date can be stored as a datetime. I suggest we support one. And since datetime is inclusive of both, i suggest we keep datetime.

**Tony**
> I agree with Jeff that we only need to support datetime. Our example in core.md was more of a demonstration of acceptable ways to represent dates within the schema. We shouldn’t need to support both. datetime is inclusive of date.

**Action**
- Remove occurrences of `Date` from the core metadata schema because `DateTime` is sufficient.

**Comment by igarousi** [comment]
Done. See commit #ba03d33.
