### ISSUE TITLE
Consistent Representative Datasets in Data Catalog

### ISSUE THREAD

**Issue by fbaig** [I-GUIDE/data-catalog#56]
**Problem**
Current datasets in the catalog are in inconsistent states. As an immediate task for the workshop is to add at least one dataset catalog along with appropriate functionality. An additional required functionality for every dataset is to have **associated usable, tested code to access and download it**.  

In addition to Following are the representative types of the datasets

1. Public, directly accessible (e.g. openly hosted on cloud)
2. Public, behind API keys and subscriptions
3. Not-public (data accessible through collaborations) internally accessible to allowed list

**Possible Sources of Data**
- IPUMS
- NCAR
- Unidata
- Cloud Catalogs

**Comment by igarousi** [comment]
These are the links to the newly added records:

#### PUBLISHED RESOURCES ON HYDROSHARE

- https://iguide.cuahsi.io/dataset/65dcc9c7239673420509599c

  - This is a published HydroShare resource about a high-resolution map of diffuse groundwater recharge rates for Australia

- https://iguide.cuahsi.io/dataset/65dccbbd23967342050959a0

  - This is a published HydroShare resource with data about streamflow and groundwater over the Central Alps

- https://iguide.cuahsi.io/dataset/65dccc3023967342050959a2

  - This is a published HydroShare collection about Hurricane Harvey.

- ~~https://iguide.cuahsi.io/dataset/65dcca76239673420509599e~~

  - *This is a published HydroShare resource, including code and data for data-driven reservoir operation rules across the US.
It was registered successfully, but the metadata cannot be rendered. The website gets killed while trying to load and render the metadata*.
#### PLUMS
- https://iguide.cuahsi.io/dataset/65dcd92623967342050959a6
  - This is about the IPUMS IHGIS data. Note that this work has lots of funding resources. I only added two when submitting this record. We can find better ways to add the funding information.
#### CLOUD STORAGES (we already have the NWM registered in the catalog. I also included the following)
- https://iguide.cuahsi.io/dataset/65dce37e23967342050959a8
  - This is an example of data on cloud catalogs. Note that the S3 example includes lots of CSV files, and it is inefficient to add them manually. I only added two for now.
