### ISSUE TITLE
Create a SchemaOrg Example: GeoTiff

### ISSUE THREAD

**Issue by Castronova** [I-GUIDE/data-catalog#9]
Explore how SchemaOrg properties can be used to describe a GeoTiff. The outcomes of this task will be:

A document containing:

- [ ] A JSON+LD example containing required metadata
- [ ] A JSON+LD example containing recommended metadata
- [ ] A JSON+LD example for a GeoTiff stored in HydroShare

**Comment by igarousi** [comment]
The GeoTIF schema is created. Here is the link: https://github.com/I-GUIDE/data-catalog/blob/main/schema/dataset-filetype-geotiff.md
